name: Auto Update

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install uv dependencies
        working-directory: ./scraper
        run: |
          uv sync --locked --no-dev
          sudo apt-get update
          sudo apt-get install -y xvfb libgbm-dev libxkbcommon0 libasound2 libgtk-3-0
          # sudo apt-get install -y google-chrome-stable
          uv run seleniumbase install chromedriver chs
          # 给所有驱动添加执行权限
          find .venv -name "uc_driver" -o -name "chromedriver" -o -name "*driver" -type f 2>/dev/null | while read -r driver; do
            chmod +x "$driver"
            echo "Fixed permissions for: $driver"
          done

      - name: Run Update Script
        working-directory: ./scraper
        run: xvfb-run --server-args="-screen 0 1280x1024x24" uv run scraper\main.py
        timeout-minutes: 120

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update configs [skip ci]" || exit 0
          git push origin main || true
